### PR TITLE
Proposal: remove restriction on "bad words"

### PR DESCRIPTION
**Pull request by peterbourgon**
Hello. I intend this as a mechanism for discussion.

Recently I was reprimanded on the Gophers Slack for saying "shit".

> @[redacted]: Thank you. And in the teach-a-man-to-fish spirit, feel free to point me to any sort of knowledge base for this kind of basic shit :)

Brad Fitzpatrick was also reprimanded for saying "crappy".

> I'm so very sorry to those I've offended with my language. I meant to say Github's PR system is doubleplusungood. 
> https://twitter.com/bradfitz/status/697116089050771456

Perhaps there have been other incidents I'm not aware of.

I am highly motivated to keep the Gophers Slack (and other GoBridge spaces) as inclusive, friendly, and explicitly harassment-free as possible. Indeed I have asked the moderators for help a few months ago with another (rather more severe) incident, and was very grateful for your swift and unambiguous response. I felt empowered and validated.

Yet, I find this apparent outright ban on an expansive set of "bad" words to be unreasonable on its face. There are certainly words which warrant this _hausverbot_ (f—t, c—t, n—r, k—e, etc.) but crappy, shit, and even fuck are, from my position, certainly not among them. I would have no problem saying any of these words in any professional context. I've said "fuck this up" (or some variation) innumerable times on stage at conference talks, in front of what must be thousands of my professional colleagues at this point. 

Obscenity is the crutch of inarticulate motherfuckers, but it is also a celebration of our humanity, powerful and appropriate as any other idiom in the right context.

This reflexive ban is stifling to me personally, but I believe it also reflects poorly, even absurdly, on GoBridge and its spaces real and virtual. I felt like the Slack channel had been infantilized, made lesser, a place inappropriate for adult communication.

I'm requesting this policy be changed, so that I may treat the Gopher Slack and other spaces in the same way that I'd treat any other open, welcoming, and professional space. But let me be clear: I'm aware of my position of privilege in this discussion, and I'm absolutely open to the idea that there's something here that I haven't considered, or considered fully. Please know that I'm coming from a position of good faith.

Thanks for your attention.

### CODE REVIEW

**Comment by mnzt** [comment]
:+1:

Often or not I'll be called out for saying a ''bad word" which I didn't know was a bad word.

**Comment by theckman** [comment]
I've been reprimanded by the same community. I raised a similar objection with the word `crap` being on the list. Here is my exchange:

```
REDACTED [15:03] 
Hi Tim. The word 'crap' is on the bad word list. I know it seems innocent but I need to moderate the language without subjection.

theckman [15:12] 
It is innocent. How do I propose a community modification of the "bad word" list?

REDACTED [15:20] 
We use a list from Google. Again so it is not subjective.

theckman [15:21] 
I guess that's the choice you have as a community organizer. ¯\_(ツ)_/¯

[15:21] 
Seems silly to me to be so restrictive. And more abrasive than the word used.

REDACTED [15:22] 
If you could please refrain from using words from the list it would be appreciated. If you want to start this conversation the CoC contains the list of admins you can talk with. Just letting you I have very strong opinions on this issue.

theckman [15:25] 
Oh don't we all. :smile:
```

**Comment by DanielHeath** [comment]
A list from Google is still a subjective list (assuming Google employed a human being to put the list together, or at least to write the code which does it).

According to the current list:
 - The words '**gay**' and '**lesbian**' are wrong (which is flatly offensive)
 - Gay pride groups are wrong (e.g. **Dykes** on bikes)
 - Garbage collection tuning is wrong (if you need to trade off latency/space there are **knobs** you can turn)
 - References to historical events in our industry are wrong (IBM contributed software and hardware assistance to the **nazis**)

**Comment by adg** [comment]
FWIW, it's not a word list from Google. It's a word list that someone reverse engineered out of a Google product. The list was certainly not devised for this purpose.

**Comment by benjamin-rood** [comment]
As _literally_ the worst offender on the slack (you can ask REDACTED yourselves), I can't believe I am going to defend the CoC in general, but I am. Daniel Heath's points are entirely sensible, but, I'm sorry, Peter, I fundamentally disagree.

Like a character from [Deadwood](https://youtu.be/LBMsXcSTi4s), I too like to enjoy the full range of expression. However, as I said at one of the numerous times I have been 'flagged':

> Given how absolutely out of control things are online these days, the only way the awful is going to be curbed is by being strict.

There has been zero **harm** by constraining the use bad words. Every single case is individually reviewed by a human, with discretion.

In every single case I have been 'pinged', I merely swapped out the offending word for a **polite** euphemism. That's the key word: **polite.** There should be higher value on Polite, civilised spaces.

As was discussed just recently on #random:

>Person C [03:46] 
>however i think it's ok to be able to edit some times :simple_smile: (it can happen you did something you regret and rather than always have it, it might be ok to remove it yourself)(edited)
>
>Person B [03:46] 
>just correct on the next line like we always have :wink:
>the problem is you can be asked to edit yourself because someone's sense of humor is off that day or whatever
>mine or the person who felt it might be offensive, whosever
>
>Person C [03:48] 
>well, there's a code of conduct, so if you breach it it might be better to fix it yourself. If someone is not getting the context maybe you can also try to understand their point of view....
>
>Person A [03:50] 
>with or without [self] editing, I think correcting things that might discourage other people to participate is good
>
>Person A [03:57] 
>I personally think keeping the community welcoming is in everybody’s interest :simple_smile:
that means we sometimes have to correct some of our behaviours, because people with different contexts or backgrounds might be put off by them
>but I believe it’s worth it
>
>Person B [03:58] 
>I can agree it wasn't mature, no argument there...
>
>Person A [03:58] 
>sometimes is not even about maturity, we can do some silly stuff that doesn’t discourage anybody, and that’s ok

Which goes to show that the discussion about these things is active already.

Are there some things that descend to the level of the absurd? Yes. 

On Jan 2nd, I did one of the following:

gopher-shit-msg  gopher-shit-reaction

To which the dialogue went:

gopher-shit-discussion

Now, the objection is the definition of _banal inanity._ But, we have twitter, we have youtube comment ("The Horror") we have every other forum on the entirety of the internet to have free reign, right or wrong.

The slack is not a public forum, it's actually a private one, and as such, it has rules. All rules when slavishly followed, are absurd. But even so, there's plenty of silliness and gifs and other channel pollution. I know that I've tried to tease Peter multiple times and you've refused to rise to the bait (maybe it wasn't original enough, or, _too original_?)...

At the end of the day, you have to judge on the _spirit_ of the rules. By those terms, I find nothing harmful.

**Comment by nathany** [comment]
> Hello. I intend this as a mechanism for discussion.

Good. That is why this word list has been placed in the open.

> Brad Fitzpatrick was also reprimanded for saying "crappy".

The admins of the Slack team intend to revise the list to remove "kid" words.

> There are certainly words which warrant this hausverbot...

Yet this pull request removes said words from the list. :confused: 

> a place inappropriate for adult communication

Do you choose different words when kids are around? This is the Internet. How do you know if the people you're talking to are adults or 13-year olds?

internet_dog

**Comment by peterbourgon** [comment]
> Yet this pull request removes said words from the list. :confused:

I would be happy to re-add the list with the words I think qualify i.e. primarily racial or cultural epithets, but then we enter into a negotiation about relative levels of offense, which I predict will be nonproductive. And I challenge the appropriateness or efficacy of an explicit list of banned words. Based on my own positive experience, I have absolute trust in the moderators and community to identify and appropriately deal with those incidents as they occur, without such a list.

> Do you choose different words when kids are around? This is the Internet. How do you know if the people you're talking to are adults or 13-year olds?

I can't make a generalized statement about my behavior, as it's always context-dependent. But given a room full of mostly-adults and a minority of 12+ year olds, I certainly wouldn't squelch a contextually-appropriate use of fuck, e.g. "Clock skew will fuck up your invariants really badly". I have the reasonable expectation that a general community space for a low-level programming language is a room full of mostly-adults.

**Comment by benjamin-rood** [comment]
>I can't make a generalized statement about my behavior, as it's always context-dependent. But given a room full of mostly-adults and a minority of 12+ year olds, I certainly wouldn't squelch a contextually-appropriate use of fuck, e.g. "Clock skew will fuck up your invariants really badly". I have the reasonable expectation that a general community space for a low-level programming language is a room full of mostly-adults.

Then it would be a seemingly rare case of you being intellectually lazy, so much so that I'm not sure if you aren't being somewhat disingenuous, Peter. However, if I was a parent in that imaginary situation who bought my kid along, I would be disappointed, especially if you realised that my kid was there. There is no _need_ for you to do that. Especially when the fact of the matter is, in this field, you are one of the most well-spoken, high-concept folks out there. That's the problem with your position: You are not being demonstrably abridged at all by self-censoring, and you are not able to be persuasive that there is any injury done by this policy. There's nothing stopping you from creating a thousand brilliantly colourful [Captain Haddock](https://s-media-cache-ak0.pinimg.com/736x/fb/2f/34/fb2f34edba6de2bd59a99763946ce111.jpg) speech bubbles. Don't you think you are making a mountain out of a molehill? And what does that have to do with Gophers!? :wink:

However, I don't think that "We might corrupt the minds of the children" is actually your argument, Nathan, and if it is, then it's rather insufficient.  I'm guessing it's a casual, shorthand appeal to a shared reservation that is not as _en vogue_ as you might have hoped, in lieu of the real argument. Having been clearly on the receiving end of these, what could be at worst described as _harmless_ and _silly_ interruptions by a friendly but strict librarian, to a greater degree and frequency than anyone else who has entered this discussion so far, I can say that the real argument that has been communicated to me lies in believing strongly in the virtues of a quote-unquote _clean_ space as engendering the inviting, welcoming environment and discourse as much as anything else.

Again:

>This reflexive ban is stifling to me personally, but I believe it also reflects poorly, even absurdly, on GoBridge and its spaces real and virtual. I felt like the Slack channel had been infantilized, made lesser, a place inappropriate for adult communication.

Look up Samuel Taylor Coleridge and the difference between creative and fanciful associations. 
As possibly the world's biggest David Milch fan (a grandiose claim I can back up with > 10,000 words from my reverential MFA research), I sympathise with your appreciation for the tonality, range, the playfulness and emotional emphasis of cursing... but to say you are "stifled" is borderline self-indulgence.

>I have the reasonable expectation that a general community space for a low-level programming language is a room full of mostly-adults.

That last one is starting to sound like a demand to a service provider, and not entirely congruent with the position you originally professed.  But, as someone who is admittedly on the very bottom of the stack, perhaps I have a lot to learn.

**Comment by azr** [comment]
To add my 50cts here I'd say that putting all those word on the same level is kinda not clever.
There aren't 2 sides of the English language, there is just context and phrasing.

We should try to focus on why you put them in the first place; I believe it's to avoid people from being offending without having to read every single message.

Ex: I made a crappy line of code. *not offending*
Vs: You are the worst programmer on earth. *very offending*

So now, lets implement a phrase parser in golang to fix this.

**Comment by sprstnd** [comment]
It is all relative, saying 'good ole boys' to a generation of black men might be offense yet endearing to another generation of white men...The logical conclusion would to be sensible. However who draws that sensible line? It is all relative.

**Comment by DanielHeath** [comment]
@sprstnd Gobridge is not aiming for an imaginary middle ground. It exists to empower **underrepresented** communities.

If a behavior is discouraging the people Gobridge is trying to help, then it is not welcome at Gobridge.

**Comment by DanielHeath** [comment]
As far as kids go - parental consent is a pretty significant factor in what a 13 year old gets to do.

Does anyone want to argue that dropping the f-word into a conversation isn't going to affect whether a parent lets their kid attend?

**Comment by theckman** [comment]
@DanielHeath as someone who openly used profanity at an age much younger than 13, it would not impact me. Profanity is not obscene to me.

**Comment by DanielHeath** [comment]
@theckman cool, you swore as a kid. I guess that means there are no parents who would stop their kids attending due to profanity.

**Comment by theckman** [comment]
@DanielHeath my point was that some may argue against that.

**Comment by theckman** [comment]
@benjamin-rood I think there may be some merit in being sensitive about some words. My objection is with `crap`, amongst others. But that's the one I am calling out.

**Comment by benjamin-rood** [comment]
@theckman Well, as has already been made clear by Nathan, such terms are going to be 'whitelisted' (I've also had that verified elsewhere) – there is no disagreement there.

**Comment by ardan-bkennedy** [comment]
We have revised the banned word list and made it our own. We also started a new flagged word list. The banned word list are words that can’t be used in any context at any time in the public channels. The flagged word list are words we get notified about and require more context to determine how they were used. We are counting on everyone’s support to keep the GoBridge online communities safe and welcoming. Thank You

**Comment by ardan-bkennedy** [comment]
I have removed the word list. If someone is reported we will look at it then. I do hope people use constraint and minimize their use of language that could offend others. Please, let's all think about everyone who is there participating.

**Comment by carlisia** [comment]
Thank you for the very thoughtful and respectful discussion, and for taking the time to share with us your perspectives. The admins have listened and agreed with the removal of the flagged and banned words lists. 

We ask that you keep on being mindful of appropriate language and behavior, and continue reporting to us when you see infractions to the spirit of the CoC. We can use everyone's help.

**Pull request closed without merging**
